import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import styles from "../styles/Home.module.css";
import AboutMe from "../views/AboutMe/AboutMe";
import Projects from "../views/Projects/Projects";
import Technologies from "../views/Technologies/Technologies";
import Image from "next/image";

import Welcome from "../views/Welcome/Welcome";
import LayoutSwitch from "../layout/LayoutSwitch";

export default function Home({ introOver, setIntroOver, prevScrollPos }) {
  return (
    <div className="h-full relative">
      <Head>
        <title>Develop With Derek</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/*         <link
          href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=optional"
          rel="stylesheet"
        /> */}

        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#1193b8" />
        <meta name="msapplication-TileColor" content="#2d89ef" />
        <meta name="theme-color" content="#1a9def" />
      </Head>
      <main className={`h-full ${introOver ? "" : "hidden"}`}>
        <div className={` h-full`}>
          <Welcome introOver={introOver} />
          {/*     <AboutMe /> */}
          <LayoutSwitch setIntroOver={() => null} />
        </div>
      </main>
    </div>
  );
}
