import Head from "next/head";
import { Navbar } from "@components";
import { useWindowEffectsContext } from "@context/WindowEffectsContext";
import { useMediaQuery } from "@hooks";
import { Terminal, TerminalShell } from "@components";
import { Welcome, Technologies, Projects, AboutMe, Certificates } from "@views";
import { mdMediaQuery } from "@pages/app_constants";

export default function DWD() {
  const { terminalAnimStart, terminalAnimOver } = useWindowEffectsContext();

  const [mdViewport] = useMediaQuery(mdMediaQuery);
  const mobileLayout = (
    <>
      <div className={`overflow-hidden relative flex flex-col justify-center items-center`}>
        <AboutMe />
        <Projects />
        <Technologies />
        <Certificates />
      </div>
    </>
  );

  const content = () =>
    mdViewport ? <Terminal terminalAnimStart={terminalAnimStart} terminalAnimOver={terminalAnimOver} /> : mobileLayout;

  return (
    <>
      <Head>
        <title>Develop With Derek</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#1193b8" />
        <meta name="msapplication-TileColor" content="#2d89ef" />
        <meta name="theme-color" content="#1a9def" />
      </Head>
      <Navbar />
      <main className={"min-h-screen"}>
        <Welcome />
        {mdViewport !== null && content()}
      </main>
    </>
  );
}

// TODO: Figure out anchor link jumping when manually entering
